// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.webessay.model;

import com.webessay.model.MessagesPK;
import java.io.Serializable;

privileged aspect MessagesPK_Roo_Serializable {
    
    declare parents: MessagesPK implements Serializable;
    
    private static final long MessagesPK.serialVersionUID = 1L;
    
}
