// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.webessay.model;

import com.webessay.model.MessagesPK;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MessagesPK_Roo_Configurable {
    
    declare @type: MessagesPK: @Configurable;
    
}
